controller_manager:
  ros__parameters:
    update_rate: 50  
    use_sim_time: true

    wheel_controller:
      type: velocity_controllers/JointGroupVelocityController

wheel_controller:
  ros__parameters:
    joints:
      - wheel_x1_joint
      - wheel_x2_joint
      - wheel_x3_joint
      - wheel_x4_joint
      - wheel_y1_joint
      - wheel_y2_joint
      - wheel_y3_joint
      - wheel_y4_joint
    
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity
